package mpe;

import java.io.Serializable;

public class Command implements Serializable {
	
	/**
	 * Autogenerated serial ID
	 */
	private static final long serialVersionUID = 2282916117561401433L;
	
	public
		String command;
		Object att;

}
