package mpe;

import java.io.Serializable;

//import processing.event.KeyEvent;
//import processing.event.MouseEvent;

/**
 * Serializable communication object used between processes.
 * @author Brandt Westing TACC
 *
 */
public class Command implements Serializable {
	
	/**
	 * Autogenerated serial ID
	 */
	private static final long serialVersionUID = 2282916117561401433L;
	
	public
		String command;
		Object att;
		//MouseEvent m;
		//KeyEvent k;
}
