package mpe.process;

import java.io.Serializable;
//import java.util.Vector;

public class Command implements Serializable {
	
	/**
	 * Autogenerated serial ID
	 */
	private static final long serialVersionUID = 2282916117561401433L;
	
	public
		String command;
		//Vector atts;

}
